"""把令牌渲染成 Flutter 主题 Dart 代码。

按类型分组：color → AppColors，dimension → AppSpacing。
生成的 Dart 是单一事实源的派生物，禁止手改；样式值只能来自这里（见 custom_lint 规则）。
"""
from __future__ import annotations

from dtcg2flutter.tokens import Token

_HEADER = """\
// AUTO-GENERATED by tools/dtcg2flutter. 请勿手改——改 DESIGN.md 后重新生成。
import 'package:flutter/material.dart';"""


def to_color(value: str) -> str:
    hex = value.lstrip("#")
    if len(hex) == 3:
        hex = "".join(c * 2 for c in hex)
    if len(hex) == 6:
        return f"Color(0xFF{hex.upper()})"
    if len(hex) == 8:
        return f"Color(0x{hex.upper()})"
    return f"Color(0xFF000000)  // 未支持的色值: {value}"


def to_dimension(value: str) -> str:
    s = value.replace("px", "").strip()
    try:
        f = float(s)
    except ValueError:
        return "0.0"
    return f"{f:.1f}"


def render_dart(tokens: list[Token]) -> str:
    parts = [_HEADER]
    colors = [t for t in tokens if t.type == "color"]
    dims = [t for t in tokens if t.type == "dimension"]
    if colors:
        parts.append(_class("AppColors", colors, to_color))
    if dims:
        parts.append(_class("AppSpacing", dims, to_dimension))
    return "\n\n".join(parts) + "\n"


def _class(name: str, tokens: list[Token], convert) -> str:
    from collections import Counter
    leaf_counts = Counter(t.path[-1] for t in tokens)
    lines = [f"class {name} {{"]
    for t in tokens:
        leaf = t.path[-1]
        field = leaf if leaf_counts[leaf] == 1 else "_".join(t.path)
        lines.append(f"  static const {field} = {convert(t.value)};")
    lines.append("}")
    return "\n".join(lines)
