// AUTO-GENERATED by tools/dtcg2flutter. 请勿手改——改 DESIGN.md 后重新生成。
import 'package:flutter/material.dart';

class AppColors {
  static const primary = Color(0xFF3B82F6);
  static const surface = Color(0xFFFFFFFF);
  static const onSurface = Color(0xFF1A1A1A);
  static const danger = Color(0xFFEF4444);
}

class AppSpacing {
  static const sm = 8.0;
  static const md = 16.0;
  static const lg = 24.0;
}
